import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Lens Starter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        Lens Protocol - Next.js - TypeScript - Apollo Client - Wagmi -
        Rainbowkit - Tailwind CSS starter.
      </main>
    </div>
  );
}
